# Generated by Django 3.0.5 on 2021-02-04 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210204_2151'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.UrlShort'),
        ),
    ]
