# Generated by Django 3.0.5 on 2020-05-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=200)),
                ('Short', models.CharField(max_length=15, unique=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
