# Generated by Django 3.0.5 on 2020-05-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='Short',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
