# Generated by Django 3.0.5 on 2020-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_urlshort_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshort',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
