# Generated by Django 3.0.5 on 2021-02-04 21:51

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_urlshort_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='Url',
            field=models.CharField(max_length=200, validators=[main.validators.validate_url]),
        ),
    ]
